export { capitalizeAllWords } from './capitalizeAllWords';
export { capitalizeFirstWord } from './capitalizeFirstWord';
export { inflectQuantity, inflectByNumber } from './inflect';
export { digitsOnly } from './digitsOnly';
export { computeHash } from './computeHash';
export { nondigitsOnly } from './nondigitsOnly';
export { removeExtraWhitespace } from './removeExtraWhitespace';
export { removeWhitespace } from './removeWhitespace';
export { startsWith } from './startsWith';
export * from './String-prototype-wrappers';
