export { capitalizeAllWords } from './capitalizeAllWords';
export { capitalizeFirstWord } from './capitalizeFirstWord';
export { countOccurrences } from './countOccurrences';
export { inflectQuantity, inflectByNumber } from './inflect';
export { isEnclosed } from './isEnclosed';
export { digitsOnly } from './digitsOnly';
export { computeHash } from './computeHash';
export { nondigitsOnly } from './nondigitsOnly';
export { parseEnclosed } from './parseEnclosed';
export { parseInteger } from './parseInteger';
export { randomAlphanumeric } from './randomAlphanumeric';
export { removeExtraWhitespace } from './removeExtraWhitespace';
export { removeWhitespace } from './removeWhitespace';
export { splitOnce } from './splitOnce';
export { startsWith } from './startsWith';
export * from './String-prototype-wrappers';
