export { capitalizeAllWords } from './capitalizeAllWords.js';
export { capitalizeFirstWord } from './capitalizeFirstWord.js';
export { computeHash } from './computeHash.js';
export { countOccurrences } from './countOccurrences.js';
export { digitsOnly } from './digitsOnly.js';
export { inflectByNumber,inflectQuantity } from './inflect.js';
export { isEnclosed } from './isEnclosed.js';
export { nondigitsOnly } from './nondigitsOnly.js';
export { parseEnclosed } from './parseEnclosed.js';
export { parseInteger } from './parseInteger.js';
export { randomAlphanumeric } from './randomAlphanumeric.js';
export { removeExtraWhitespace } from './removeExtraWhitespace.js';
export { removeWhitespace } from './removeWhitespace.js';
export { splitOnce } from './splitOnce.js';
export { startsWith } from './startsWith.js';
export * from './String-prototype-wrappers.js';
