import path from 'path';

import { Directory } from 'src/classes';
import type { PathLike } from 'src/functions';
import { makeTempDir } from 'src/functions';

const defaultTestDir = ['tmp', 'test'];

// Create a directory in which to place files generated by tests
export function makeTestsDir(dirPath?: PathLike | undefined): Directory {
  const testsDirPath = Directory.toPath(dirPath || defaultTestDir);

  return new Directory(process.env.CI
    ? makeTempDir('test')
    : makeTempDir(testsDirPath, { baseDir: path.resolve() })
  );
}
